import Head from 'next/head'
import Image from 'next/image'
import CardList from '../components/CardList'
import styles from '../styles/Home.module.css'

export const getStaticProps = async () => {
  const response = await fetch('https://www.reddit.com/r/react.json')
  
  const data = await response.json()
  // how did you know to map map over the response and map the .data?
  const updatedData = data.data.children.map((obj) => (
    obj.data
  ))
  console.log(updatedData)
  return {
    props: {
      updatedData
    }
    
  }
  
}

export default function Home({ updatedData }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-4xl text-center my-6 font-bold'>Latests posts to {updatedData[0].subreddit_name_prefixed}</h1>
      <div className='flex flex-col mx-auto'>
        <CardList updatedData={updatedData}/>
      </div>
      
      {/* {updatedData.map((post) => (
          <div
            className='p-4 bg-gray-200 bg-opacity-40 rounded-xl flex flex-col mb-4 w-11/12 lg:w-80' 
            key={post.id}>
            <h3 className='text-xl font-bold'>{post.title}</h3>
            <p>Author: {post.author}</p>
            <p>Comments: {post.num_comments}</p>
            <p>UpVote: {post.ups}</p>
          </div>
        ))} */}
    </div>
  )
}
